# Generated by Django 2.2 on 2021-11-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_regddd_ct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regddd',
            name='ct',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
