# Generated by Django 3.2.9 on 2021-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211119_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='regddd',
            name='district',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
